name: CD

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Yarn setup
        uses: DerYeger/yarn-setup-action@master
        with:
          node-version: 16
      - name: Generate static files
        run: yarn generate
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: static-site-artifact
          path: ./.output/public
          if-no-files-found: error
  upload-assets:
    name: Upload assets
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'created'
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: static-site-artifact
          path: ./.output/public
      - name: Zip files
        uses: montudor/action-zip@v1.0.0
        with:
          args: zip -qq -r ./noted.zip ../.output/public
      - name: Release assets
        uses: softprops/action-gh-release@v1
        with:
          files: noted.zip
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: static-site-artifact
          path: ./.output/public
      - name: Create 404.html file
        run: cp ./.output/public/200.html ./.output/public/404.html
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: ./.output/public
          clean: true
          git-config-name: Jan Müller
          git-config-email: janmueller3698@gmail.com
