name: CI

on: [pull_request, push]

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    steps:
      - name: Yarn setup
        uses: DerYeger/yarn-setup-action@master
        with:
          node-version: 16
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Yarn setup
        uses: DerYeger/yarn-setup-action@master
        with:
          node-version: 16
      - name: Build
        run: yarn generate
  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Yarn setup
        uses: DerYeger/yarn-setup-action@master
        with:
          node-version: 16
      - name: Lint
        run: yarn lint
  test:
    name: Test
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Yarn setup
        uses: DerYeger/yarn-setup-action@master
        with:
          node-version: 16
      - name: Test
        run: yarn test
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [build, lint, test]
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          token: ${{ secrets.PAT }}
      - name: Semantic release
        uses: cycjimmy/semantic-release-action@v3.0.0
        with:
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
